#!/usr/bin/env bash

source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../ci-lib.sh"

# 1) Pull source and gen build environment
gen_build_dir_with_git 'https://github.com/intel/intel-extension-for-pytorch' -b "$FRAMEWORKS_IPEX_VERSION"
setup_build_env

artifact_in "torch-*.whl"

setup_uv_venv -r requirements.txt pip *.whl

# 2) Set IPEX build configuration
CC="$(which gcc)"
export CC
CXX="$(which g++)"
export CXX
export INTELONEAPIROOT="$ONEAPI_ROOT"

# 3) Build & Archive
build_bdist_wheel
